server:
  port: ${SERVER_PORT:1010}

spring:
  application:
    name: ${APP_NAME:phrases-service}

  r2dbc:
    url: ${CONNECTION_DB_URL}
    username: ${DB_USER:openserver}
    password: ${DB_PASSWORD:123456}

logging:
  level:
    org.springframework.r2dbc: INFO